// Page 6 — Reports

function PageReports({ projects }) {
  const [type, setType] = React.useState('Monthly Executive');
  const [project, setProject] = React.useState('All Projects');
  const [from, setFrom] = React.useState('2026-04-01');
  const [to, setTo] = React.useState('2026-04-30');
  const [generated, setGenerated] = React.useState(null);

  return (
    <div className="p-6 space-y-5">
      <div>
        <h1 className="text-2xl font-bold ink-on-dark">Reports</h1>
        <p className="text-xs text-ink-500 ink-muted-on-dark mt-0.5">Generate, preview, and download daily / weekly / monthly reports</p>
      </div>

      <Card>
        <SectionTitle icon="file-plus-2" title="Generate New Report" />
        <div className="grid grid-cols-1 md:grid-cols-5 gap-3 items-end">
          <div>
            <label className="text-xs text-ink-500 ink-muted-on-dark">Type</label>
            <Select value={type} onChange={setType} options={REPORT_TYPES} className="w-full" />
          </div>
          <div>
            <label className="text-xs text-ink-500 ink-muted-on-dark">Project</label>
            <Select value={project} onChange={setProject} options={['All Projects', ...projects.map(p => p.name)]} className="w-full" />
          </div>
          <div>
            <label className="text-xs text-ink-500 ink-muted-on-dark">From</label>
            <TextField value={from} onChange={setFrom} type="date" />
          </div>
          <div>
            <label className="text-xs text-ink-500 ink-muted-on-dark">To</label>
            <TextField value={to} onChange={setTo} type="date" />
          </div>
          <Button icon="play" variant="accent" onClick={() => setGenerated({ type, project, from, to })}>Generate</Button>
        </div>

        {generated && (
          <div className="mt-4 border border-soft rounded-md p-4 surface-2">
            <div className="flex items-start justify-between">
              <div>
                <div className="text-[10px] uppercase tracking-wider text-ink-500 ink-muted-on-dark">Preview</div>
                <div className="text-base font-semibold ink-on-dark">{generated.type} — {generated.project}</div>
                <div className="text-xs text-ink-500 ink-muted-on-dark">{generated.from} → {generated.to}</div>
              </div>
              <div className="flex items-center gap-2">
                <button className="p-2 rounded-md border border-soft surface hover:bg-ink-100" title="Download Excel">
                  <Icon name="file-spreadsheet" size={16} />
                </button>
                <button className="p-2 rounded-md border border-soft surface hover:bg-ink-100" title="Download PDF">
                  <Icon name="file-text" size={16} />
                </button>
              </div>
            </div>
            <div className="mt-3 placeholder-grid h-40 rounded-md border border-soft" />
          </div>
        )}
      </Card>

      <Card padding="p-0">
        <div className="px-5 pt-4 pb-2"><SectionTitle icon="folder" title="Saved Reports" /></div>
        <table className="w-full text-sm">
          <thead className="surface-2 text-[11px] uppercase tracking-wider text-ink-500 ink-muted-on-dark">
            <tr>
              <th className="text-left px-5 py-2">Type</th>
              <th className="text-left px-3 py-2">Project</th>
              <th className="text-left px-3 py-2">Generated By</th>
              <th className="text-left px-3 py-2">Date</th>
              <th className="text-right px-5 py-2">Download</th>
            </tr>
          </thead>
          <tbody>
            {SAVED_REPORTS.map(r => (
              <tr key={r.id} className="border-t border-soft hover-row">
                <td className="px-5 py-2 ink-on-dark font-medium">{r.type}</td>
                <td className="px-3 py-2 text-xs">{r.project}</td>
                <td className="px-3 py-2 text-xs">{r.by}</td>
                <td className="px-3 py-2 text-xs tnum">{r.date}</td>
                <td className="px-5 py-2 text-right">
                  <div className="inline-flex items-center gap-1.5">
                    {r.formats.includes('xlsx') && <button className="p-1.5 rounded border border-soft hover:bg-ink-100" title="Excel"><Icon name="file-spreadsheet" size={14} /></button>}
                    {r.formats.includes('pdf')  && <button className="p-1.5 rounded border border-soft hover:bg-ink-100" title="PDF"><Icon name="file-text" size={14} /></button>}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>
    </div>
  );
}

Object.assign(window, { PageReports });
